# Generated by Django 2.1.5 on 2020-09-01 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0002_project_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': '角色', 'verbose_name_plural': '角色'},
        ),
    ]
