# Generated by Django 2.1.5 on 2020-09-03 07:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0003_auto_20200901_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='server',
            field=models.ForeignKey(default=1, max_length=32, on_delete=django.db.models.deletion.DO_NOTHING, to='app02.Host', verbose_name='服务器'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, '在建'), (2, '验收')], default=1, verbose_name='状态'),
        ),
    ]
