# Generated by Django 2.1.5 on 2020-09-03 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0005_remove_project_server'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
