# Generated by Django 2.1.5 on 2020-09-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0006_remove_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, '在建'), (2, '验收')], default=1, verbose_name='状态'),
        ),
    ]
