# Generated by Django 2.1.5 on 2020-09-03 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0007_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='server',
            field=models.ForeignKey(default=1, max_length=32, on_delete=django.db.models.deletion.DO_NOTHING, to='app02.Host', verbose_name='服务器'),
            preserve_default=False,
        ),
    ]
